services:
  - type: web
    name: nazoratbot-telegram
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.main
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_MODE
        value: webhook
      - key: WEBHOOK_URL
        value: https://bojxonanazoratibot.onrender.com
      - key: WEBHOOK_PATH
        value: /webhook
      - key: PERMISSION_RULES_PATH
        value: data/permission_rules.json
      - key: TZ
        value: Asia/Tashkent
      - key: DATABASE_PATH
        value: data/bot_data.sqlite3
      - key: TERMS_IMAGE_PATH
        value: assets/foydalanish_shartlari.png
      - key: TERMS_PDF_PATH
        value: assets/foydalanish_shartlari.pdf
      - key: TERMS_PHOTO_FILE_ID
        sync: false
      - key: USER_DATABASE_URL
        sync: false
