from __future__ import annotations

from .base import VehicleRecord


def _doc(
    kind: str,
    number: str,
    from_post: str,
    start_date: str,
    deadline: str,
    state: str,
    level: str = "ok",
    to_post: str | None = None,
) -> dict[str, str | None]:
    return {
        "type": kind,
        "number": number,
        "from_post": from_post,
        "start_date": start_date,
        "to_post": to_post,
        "deadline": deadline,
        "state": state,
        "level": level,
    }


def _check(level: str = "ok", text: str = "yo'q") -> dict[str, str]:
    return {"level": level, "text": text}


DEMO_VEHICLES: dict[str, VehicleRecord] = {
    "01A123BB": {
        "plate": "01A123BB",
        "origin": "Milliy",
        "vehicle_type": "Yengil avtomobil",
        "status": "ok",
        "conclusion": "Transport bo'yicha nazoratdagi yuk hujjati aniqlanmadi.",
        "docs": [],
        "debt": _check(),
        "fine": _check(),
        "ban": _check(),
    },
    "01B555CC": {
        "plate": "01B555CC",
        "origin": "Milliy",
        "vehicle_type": "Yuk mashinasi",
        "status": "info",
        "conclusion": "Eksport 3 qadam hujjati nazoratga olingan. Belgilangan chiqish postida nazoratdan yechish talab etiladi.",
        "docs": [
            _doc(
                "Eksport 3 qadam",
                "EK20260382842",
                "\"Sergeli\" TIF BP",
                "12.07.2026",
                "15.07.2026 gacha",
                "Yuk yetkazib berilmagan",
                "ok",
                "\"G'isht ko'prik\" ChBP",
            )
        ],
        "debt": _check(),
        "fine": _check(),
        "ban": _check(),
    },
    "01B556CC": {
        "plate": "01B556CC",
        "origin": "Milliy",
        "vehicle_type": "Yuk mashinasi",
        "status": "warn",
        "conclusion": "Eksport yuki bilan chiqayotgan transport uchun Eksport 3 qadam hujjati rasmiylashtirilishi kerak.",
        "docs": [],
        "expected_missing": "Eksport 3 qadam",
        "cargo_control_missing_warning": True,
        "debt": _check(),
        "fine": _check(),
        "ban": _check(),
    },
    "774ABC77": {
        "plate": "774ABC77",
        "origin": "Xorijiy",
        "vehicle_type": "Yuk mashinasi",
        "status": "danger",
        "conclusion": "Nazoratdan yechilmagan va muddati o'tgan tranzit deklaratsiya mavjud. Belgilangan bojxona postida nazoratdan yechish talab etiladi.",
        "docs": [
            _doc(
                "Tranzit deklaratsiya",
                "AT20260497727",
                "\"Oybek\" ChBP",
                "11.07.2026",
                "12.07.2026 da tugagan",
                "Muddati o'tgan",
                "danger",
                "\"Toshkent tovar\" TIF",
            ),
            _doc(
                "Majburiyatnoma",
                "MB20262169811",
                "\"Oybek\" ChBP",
                "11.07.2026",
                "09.10.2026 gacha",
                "Muddati o'tmagan",
            ),
        ],
        "debt": _check("warn", "yig'im hisoblanishi mumkin"),
        "fine": _check(),
        "ban": _check("warn", "tranzit deklaratsiya nazoratdan yechilishi kerak"),
    },
    "999KZ777": {
        "plate": "999KZ777",
        "origin": "Xorijiy",
        "vehicle_type": "Yuk mashinasi",
        "status": "warn",
        "conclusion": "Yuk bo'yicha faol nazorat hujjati aniqlanmadi. Transport yuk bilan harakatlanayotgan bo'lsa, tegishli hujjatlar rasmiylashtirilishi kerak.",
        "docs": [
            _doc("Majburiyatnoma", "MB20262170455", "\"Daut-ota\" ChBP", "13.07.2026", "11.10.2026 gacha", "Muddati o'tmagan")
        ],
        "cargo_control_missing_warning": True,
        "debt": _check(),
        "fine": _check(),
        "ban": _check(),
    },
    "A123BC01": {
        "plate": "A123BC01",
        "origin": "Xorijiy",
        "vehicle_type": "Yengil avtomobil",
        "status": "info",
        "conclusion": "Majburiyatnoma muddati o'tmagan.",
        "docs": [
            _doc("Majburiyatnoma", "MB20262169811", "\"G'isht ko'prik\" ChBP", "25.06.2026", "23.09.2026 gacha", "Muddati o'tmagan")
        ],
        "debt": _check(),
        "fine": _check(),
        "ban": _check(),
    },
    "B777DD09": {
        "plate": "B777DD09",
        "origin": "Xorijiy",
        "vehicle_type": "Yengil avtomobil",
        "status": "danger",
        "conclusion": "Majburiyatnoma muddati o'tgan. Bojxona postida majburiyatnoma holatini tekshirish talab etiladi.",
        "docs": [
            _doc("Majburiyatnoma", "MB20261998877", "\"Oybek\" ChBP", "05.04.2026", "05.07.2026 da tugagan", "Muddati o'tgan", "danger")
        ],
        "debt": _check("warn", "amaldagi BHM asosida hisoblanadi"),
        "fine": _check(),
        "ban": _check("warn", "bojxona postida tekshirish talab etiladi"),
    },
    "270KZ777": {
        "plate": "270KZ777",
        "origin": "Xorijiy",
        "vehicle_type": "Yuk mashinasi",
        "status": "info",
        "conclusion": "YUBNK nazoratga olingan. Belgilangan postda nazoratdan yechish talab etiladi.",
        "docs": [
            _doc("YUBNK", "27014/13.07.2026/03002", "\"Daut-ota\" ChBP", "13.07.2026", "16.07.2026 gacha", "Muddati o'tmagan", "ok", "\"Buxoro\" TIF BP")
        ],
        "debt": _check(),
        "fine": _check(),
        "ban": _check(),
    },
    "888KZ777": {
        "plate": "888KZ777",
        "origin": "Xorijiy",
        "vehicle_type": "Yuk mashinasi",
        "status": "danger",
        "conclusion": "YUBNK muddati o'tgan. Belgilangan postda nazoratdan yechish talab etiladi.",
        "docs": [
            _doc("YUBNK", "27014/09.07.2026/02888", "\"Daut-ota\" ChBP", "09.07.2026", "12.07.2026 da tugagan", "Muddati o'tgan", "danger", "\"Buxoro\" TIF BP")
        ],
        "debt": _check("warn", "yig'im hisoblanishi mumkin"),
        "fine": _check(),
        "ban": _check("warn", "YUBNK nazoratdan yechilishi kerak"),
    },
    "01C888EE": {
        "plate": "01C888EE",
        "origin": "Milliy",
        "vehicle_type": "Yengil avtomobil",
        "status": "warn",
        "conclusion": "Yuk bo'yicha nazoratdagi hujjat aniqlanmadi. Yo'l harakati xavfsizligi bo'yicha jarima mavjud.",
        "docs": [],
        "debt": _check(),
        "fine": _check("warn", "2 ta, jami 825 000 so'm"),
        "ban": _check(),
    },
    "01D444FF": {
        "plate": "01D444FF",
        "origin": "Milliy",
        "vehicle_type": "Yengil avtomobil",
        "status": "danger",
        "conclusion": "Majburiy ijro byurosi tomonidan ushbu avtotransport vositasini O'zbekiston Respublikasidan tashqariga olib chiqishga taqiq qo'yilgan.",
        "docs": [],
        "debt": _check(),
        "fine": _check(),
        "ban": _check("danger", "Majburiy ijro byurosi qarori asosida taqiq mavjud"),
    },
    "T1234AB": {
        "plate": "T1234AB",
        "origin": "Xorijiy",
        "vehicle_type": "Tirkama",
        "status": "info",
        "conclusion": "Tirkama bo'yicha majburiyatnoma muddati o'tmagan.",
        "docs": [
            _doc("Majburiyatnoma", "MB20262171234", "\"Oybek\" ChBP", "11.07.2026", "09.10.2026 gacha", "Muddati o'tmagan")
        ],
        "debt": _check(),
        "fine": _check(),
        "ban": _check(),
    },
    "70ABC01": {
        "plate": "70ABC01",
        "origin": "Xorijiy",
        "vehicle_type": "Yengil avtomobil",
        "status": "warn",
        "conclusion": "Majburiyatnoma muddati tugashiga 3 kun qolgan. Muddat tugashidan oldin bojxona postida tekshirish tavsiya etiladi.",
        "docs": [
            _doc("Majburiyatnoma", "MB20262170003", "\"G'isht ko'prik\" ChBP", "17.04.2026", "16.07.2026 gacha", "Tugashiga 3 kun qoldi", "warn")
        ],
        "debt": _check(),
        "fine": _check(),
        "ban": _check(),
    },
    "TR9999KZ": {
        "plate": "TR9999KZ",
        "origin": "Xorijiy",
        "vehicle_type": "Tirkama",
        "status": "warn",
        "conclusion": "Tirkama bo'yicha majburiyatnoma muddati tugashiga 3 kun qolgan. Muddat tugashidan oldin bojxona postida tekshirish tavsiya etiladi.",
        "docs": [
            _doc("Majburiyatnoma", "MB20262171299", "\"Oybek\" ChBP", "17.04.2026", "16.07.2026 gacha", "Tugashiga 3 kun qoldi", "warn")
        ],
        "debt": _check(),
        "fine": _check(),
        "ban": _check(),
    },
    "555TR555": {
        "plate": "555TR555",
        "origin": "Xorijiy",
        "vehicle_type": "Yuk mashinasi",
        "status": "info",
        "conclusion": "Tranzit deklaratsiya nazoratda. Yuk belgilangan postga yetkazilgach, hujjat nazoratdan yechilishi kerak.",
        "docs": [
            _doc("Tranzit deklaratsiya", "AT20260555111", "\"Daut-ota\" ChBP", "13.07.2026", "16.07.2026 gacha", "Yuk yetkazib berilmagan", "ok", "\"Toshkent tovar\" TIF"),
            _doc("Majburiyatnoma", "MB20262175551", "\"Daut-ota\" ChBP", "13.07.2026", "11.10.2026 gacha", "Muddati o'tmagan"),
        ],
        "debt": _check(),
        "fine": _check(),
        "ban": _check(),
    },
    "03Z333ZZ": {
        "plate": "03Z333ZZ",
        "origin": "Milliy",
        "vehicle_type": "Yuk mashinasi",
        "status": "danger",
        "conclusion": "Eksport 3 qadam hujjati muddati o'tgan. Belgilangan bojxona postida nazoratdan yechish talab etiladi.",
        "docs": [
            _doc("Eksport 3 qadam", "EK20260333333", "\"Sergeli\" TIF BP", "10.07.2026", "12.07.2026 da tugagan", "Muddati o'tgan", "danger", "\"G'isht ko'prik\" ChBP")
        ],
        "debt": _check("warn", "hisoblanishi mumkin"),
        "fine": _check(),
        "ban": _check("warn", "hujjat nazoratdan yechilishi kerak"),
    },
    "04Q444QQ": {
        "plate": "04Q444QQ",
        "origin": "Milliy",
        "vehicle_type": "Yuk mashinasi",
        "status": "warn",
        "conclusion": "Yuk bo'yicha nazoratdagi hujjat aniqlanmadi. Bojxona yig'imlaridan qarzdorlik mavjud.",
        "docs": [],
        "cargo_control_missing_warning": True,
        "debt": _check("warn", "bor - 1 240 000 so'm"),
        "fine": _check(),
        "ban": _check(),
    },
    "05P555PP": {
        "plate": "05P555PP",
        "origin": "Milliy",
        "vehicle_type": "Yengil avtomobil",
        "status": "warn",
        "conclusion": "Yuk bo'yicha nazoratdagi hujjat aniqlanmadi. Bojxona yig'imlaridan qarzdorlik mavjud.",
        "docs": [],
        "debt": _check("warn", "bor - 580 000 so'm"),
        "fine": _check(),
        "ban": _check(),
    },
    "10H010HH": {
        "plate": "10H010HH",
        "origin": "Xorijiy",
        "vehicle_type": "Yuk mashinasi",
        "status": "warn",
        "conclusion": "YUBNK nazoratda. Bojxona yig'imlaridan qarzdorlik mavjud.",
        "docs": [
            _doc("YUBNK", "27014/13.07.2026/03077", "\"Daut-ota\" ChBP", "13.07.2026", "16.07.2026 gacha", "Muddati o'tmagan", "ok", "\"Navoiy\" TIF BP")
        ],
        "debt": _check("warn", "bor - 2 100 000 so'm"),
        "fine": _check(),
        "ban": _check(),
    },
    "60BUS60": {
        "plate": "60BUS60",
        "origin": "Xorijiy",
        "vehicle_type": "Avtobus",
        "status": "info",
        "conclusion": "Majburiyatnoma muddati o'tmagan.",
        "docs": [
            _doc("Majburiyatnoma", "MB20262176060", "\"Yallama\" ChBP", "20.06.2026", "18.09.2026 gacha", "Muddati o'tmagan")
        ],
        "debt": _check(),
        "fine": _check(),
        "ban": _check(),
    },
    "77L777LL": {
        "plate": "77L777LL",
        "origin": "Xorijiy",
        "vehicle_type": "Yuk mashinasi",
        "status": "info",
        "conclusion": "Tranzit deklaratsiya nazoratda. Belgilangan postda nazoratdan yechish talab etiladi.",
        "docs": [
            _doc("Tranzit deklaratsiya", "AT20260777777", "\"Oybek\" ChBP", "13.07.2026", "15.07.2026 gacha", "Yuk yetkazib berilmagan", "ok", "\"Toshkent tovar\" TIF"),
            _doc("Majburiyatnoma", "MB20262177777", "\"Oybek\" ChBP", "13.07.2026", "11.10.2026 gacha", "Muddati o'tmagan"),
        ],
        "debt": _check(),
        "fine": _check(),
        "ban": _check(),
    },
    "A000AA01": {
        "plate": "A000AA01",
        "origin": "Xorijiy",
        "vehicle_type": "Noma'lum",
        "status": "warn",
        "conclusion": "Xorijiy transport bo'yicha majburiyatnoma aniqlanmadi. Bojxona postida qayta tekshirish talab etiladi.",
        "docs": [],
        "debt": _check(),
        "fine": _check(),
        "ban": _check(),
    },
    "22X222XX": {
        "plate": "22X222XX",
        "origin": "Milliy",
        "vehicle_type": "Yuk mashinasi",
        "status": "info",
        "conclusion": "Eksport 3 qadam hujjati nazoratga olingan. Belgilangan chiqish postida nazoratdan yechish talab etiladi.",
        "docs": [
            _doc("Eksport 3 qadam", "EK20260444222", "\"Sergeli\" TIF BP", "13.07.2026", "15.07.2026 gacha", "Muddati o'tmagan", "ok", "\"Yallama\" ChBP")
        ],
        "debt": _check(),
        "fine": _check(),
        "ban": _check(),
    },
    "06M606MM": {
        "plate": "06M606MM",
        "origin": "Milliy",
        "vehicle_type": "Yuk mashinasi",
        "status": "danger",
        "conclusion": "Sud tomonidan ushbu avtotransport vositasini chet elga olib chiqishga cheklov qo'yilgan.",
        "docs": [],
        "debt": _check(),
        "fine": _check("warn", "1 ta, jami 375 000 so'm"),
        "ban": _check("danger", "Sud qarori asosida boshqa taqiq mavjud"),
    },
    "30BUS01": {
        "plate": "30BUS01",
        "origin": "Milliy",
        "vehicle_type": "Avtobus",
        "status": "ok",
        "conclusion": "Transport bo'yicha nazoratdagi yuk hujjati va boshqa cheklov aniqlanmadi.",
        "docs": [],
        "debt": _check(),
        "fine": _check(),
        "ban": _check(),
    },
    "KZ12345": {
        "plate": "KZ12345",
        "origin": "Xorijiy",
        "vehicle_type": "Yuk mashinasi",
        "status": "warn",
        "conclusion": "Tranzit deklaratsiya nazoratda, majburiyatnoma muddati tugashiga 3 kun qoldi.",
        "docs": [
            _doc("Tranzit deklaratsiya", "AT20260999123", "\"Daut-ota\" ChBP", "13.07.2026", "16.07.2026 gacha", "Yuk yetkazib berilmagan", "ok", "\"Oybek\" ChBP"),
            _doc("Majburiyatnoma", "MB20262171230", "\"Daut-ota\" ChBP", "17.04.2026", "16.07.2026 gacha", "Tugashiga 3 kun qoldi", "warn"),
        ],
        "debt": _check(),
        "fine": _check(),
        "ban": _check(),
    },
    "RU9090A": {
        "plate": "RU9090A",
        "origin": "Xorijiy",
        "vehicle_type": "Yengil avtomobil",
        "status": "warn",
        "conclusion": "Majburiyatnoma muddati o'tmagan, lekin yo'l harakati xavfsizligi bo'yicha jarima mavjud.",
        "docs": [
            _doc("Majburiyatnoma", "MB20262179090", "\"G'isht ko'prik\" ChBP", "01.07.2026", "29.09.2026 gacha", "Muddati o'tmagan")
        ],
        "debt": _check(),
        "fine": _check("warn", "3 ta, jami 1 125 000 so'm"),
        "ban": _check(),
    },
    "TJ7777T": {
        "plate": "TJ7777T",
        "origin": "Xorijiy",
        "vehicle_type": "Yuk mashinasi",
        "status": "warn",
        "conclusion": "Yuk bo'yicha faol nazorat hujjati aniqlanmadi. Transport yuk bilan harakatlanayotgan bo'lsa, tegishli hujjatlar rasmiylashtirilishi kerak.",
        "docs": [
            _doc("Majburiyatnoma", "MB20262177771", "\"Oybek\" ChBP", "10.07.2026", "08.10.2026 gacha", "Muddati o'tmagan")
        ],
        "cargo_control_missing_warning": True,
        "debt": _check(),
        "fine": _check(),
        "ban": _check(),
    },
    "TRK111RU": {
        "plate": "TRK111RU",
        "origin": "Xorijiy",
        "vehicle_type": "Tirkama",
        "status": "danger",
        "conclusion": "Tirkama bo'yicha majburiyatnoma muddati o'tgan. Bojxona postida majburiyatnoma holatini tekshirish talab etiladi.",
        "docs": [
            _doc("Majburiyatnoma", "MB20262111109", "\"Daut-ota\" ChBP", "01.04.2026", "30.06.2026 da tugagan", "Muddati o'tgan", "danger")
        ],
        "debt": _check("warn", "hisoblanishi mumkin"),
        "fine": _check(),
        "ban": _check("warn", "bojxona postida tekshirish talab etiladi"),
    },
    "99A999AA": {
        "plate": "99A999AA",
        "origin": "Xorijiy",
        "vehicle_type": "Yuk mashinasi",
        "status": "danger",
        "conclusion": "YUBNK bo'yicha belgilangan muddat o'tgan. Belgilangan bojxona postida nazoratdan yechish talab etiladi.",
        "docs": [
            _doc("YUBNK", "27014/08.07.2026/03999", "\"Daut-ota\" ChBP", "08.07.2026", "11.07.2026 da tugagan", "Muddati o'tgan", "danger", "\"Navoiy\" TIF BP"),
            _doc("Majburiyatnoma", "MB20262199990", "\"Daut-ota\" ChBP", "08.07.2026", "06.10.2026 gacha", "Muddati o'tmagan"),
        ],
        "debt": _check("warn", "bor - 3 450 000 so'm"),
        "fine": _check(),
        "ban": _check("warn", "YUBNK nazoratdan yechilishi kerak"),
    },
    "NETERROR": {
        "plate": "NETERROR",
        "origin": "Noma'lum",
        "vehicle_type": "Noma'lum",
        "status": "neutral",
        "conclusion": "Muhim tizimlardan biri javob bermadi. Ma'lumotlar to'liq olinmagani sababli bojxona postida qayta tekshirish talab etiladi.",
        "docs": [],
        "system_error": True,
        "debt": _check("neutral", "tekshirilmadi"),
        "fine": _check("neutral", "tekshirilmadi"),
        "ban": _check("neutral", "tekshirilmadi"),
    },
}


SAMPLE_PLATES = [
    ("01A123BB", "Milliy yengil avtomobil, nazoratdagi yuk hujjati yo'q"),
    ("01B555CC", "Milliy yuk mashinasi, Eksport 3 qadam nazoratda"),
    ("01B556CC", "Milliy yuk mashinasi, Eksport 3 qadam topilmagan"),
    ("774ABC77", "Xorijiy yuk mashinasi, muddati o'tgan tranzit deklaratsiya va MB"),
    ("999KZ777", "Xorijiy yuk mashinasi, yuk nazorati yo'q, MB bor"),
    ("A123BC01", "Xorijiy yengil avtomobil, MB muddati o'tmagan"),
    ("B777DD09", "Xorijiy yengil avtomobil, MB muddati o'tgan"),
    ("270KZ777", "Xorijiy yuk mashinasi, YUBNK muddati o'tmagan"),
    ("888KZ777", "Xorijiy yuk mashinasi, YUBNK muddati o'tgan"),
    ("01C888EE", "Milliy yengil avtomobil, YHXB jarimasi bor"),
    ("01D444FF", "Milliy yengil avtomobil, MIB taqiqi bor"),
    ("T1234AB", "Xorijiy tirkama, MB muddati o'tmagan"),
    ("70ABC01", "Xorijiy yengil avtomobil, MB tugashiga 3 kun qolgan"),
    ("TR9999KZ", "Xorijiy tirkama, MB tugashiga 3 kun qolgan"),
    ("555TR555", "Xorijiy yuk mashinasi, tranzit deklaratsiya nazoratda"),
    ("03Z333ZZ", "Milliy yuk mashinasi, Eksport 3 qadam muddati o'tgan"),
    ("04Q444QQ", "Milliy yuk mashinasi, bojxona yig'imlari qarzdorligi bor"),
    ("05P555PP", "Milliy yengil avtomobil, bojxona yig'imlari qarzdorligi bor"),
    ("10H010HH", "Xorijiy yuk mashinasi, YUBNK va qarzdorlik bor"),
    ("60BUS60", "Xorijiy avtobus, MB muddati o'tmagan"),
    ("77L777LL", "Xorijiy yuk mashinasi, tranzit deklaratsiya nazoratda"),
    ("A000AA01", "Xorijiy transport, MB topilmagan"),
    ("22X222XX", "Milliy yuk mashinasi, Eksport 3 qadam nazoratda"),
    ("06M606MM", "Milliy yuk mashinasi, sud taqiqi va jarima bor"),
    ("30BUS01", "Milliy avtobus, nazorat hujjati yo'q"),
    ("KZ12345", "Xorijiy yuk mashinasi, TD va MB tugashiga 3 kun qolgan"),
    ("RU9090A", "Xorijiy yengil avtomobil, MB va YHXB jarimasi bor"),
    ("TJ7777T", "Xorijiy yuk mashinasi, yuk nazorati yo'q, MB bor"),
    ("TRK111RU", "Xorijiy tirkama, MB muddati o'tgan"),
    ("99A999AA", "Xorijiy yuk mashinasi, YUBNK muddati o'tgan va qarzdorlik bor"),
    ("NETERROR", "Tizimlardan biri javob bermagan test holati"),
]
